install: gem install 'json_pure'
script: ''
deploy:
  edge: 
    source: s-matyukevich/dpl
    branch: master
  provider: cloudfoundry
  refresh_token: 'eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI0NzgyYzFkNS1iZmQxLTRmZTEtOGVhYS1hMDg4NzEyOTM4MTEtciIsInN1YiI6Ijk1MzZjYmI0LTUzZjEtNGQ3ZS05YWQzLTNiYzlhYzZkODhkZCIsInNjb3BlIjpbIm9wZW5pZCIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciIsInJvdXRpbmcucm91dGVyX2dyb3Vwcy5yZWFkIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbG91ZF9jb250cm9sbGVyLndyaXRlIiwiZG9wcGxlci5maXJlaG9zZSIsInNjaW0ud3JpdGUiXSwiaWF0IjoxNDY4MTc2NjcxLCJleHAiOjE0NzA3Njg2NzEsImNpZCI6ImNmIiwiY2xpZW50X2lkIjoiY2YiLCJpc3MiOiJodHRwOi8vdWFhLjUyLjUzLjIxNy4xOTMueGlwLmlvL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJvcmlnaW4iOiJ1YWEiLCJ1c2VyX2lkIjoiOTUzNmNiYjQtNTNmMS00ZDdlLTlhZDMtM2JjOWFjNmQ4OGRkIiwicmV2X3NpZyI6Ijg5YjgyZjFkIiwiYXVkIjpbImNmIiwib3BlbmlkIiwic2NpbSIsImNsb3VkX2NvbnRyb2xsZXIiLCJ1YWEiLCJyb3V0aW5nLnJvdXRlcl9ncm91cHMiLCJwYXNzd29yZCIsImRvcHBsZXIiXX0.NtkXPYcZxdtaFPDq7XR_xnYpP_26CoXRXRJ6u0NdiPCRaAoYlsT8dhJWGsuRMUDRqoHrTzRQx67cucOSw92sA5TjzQeL0n5GvdAO8vVzG1Or-b10dMxUnqRMZ7KinYLEVszHZjfXsc1AMzfACq1U19-VB6K1IWAebab4JrKJfXo'
  api: https://api.52.53.217.193.xip.io
  organization: pcfdev-org
  space: pcfdev-space
  skip_ssl_validation: true
  on:
    branch: travis    
