#!/bin/bash -e

wget https://github.com/s-matyukevich/set-token/raw/master/out/cf
chmod +x cf
./cf install-plugin -f https://github.com/s-matyukevich/set-token/raw/master/out/set-token

./cf api http://api.52.53.246.25.xip.io --skip-ssl-validation
./cf set-token -c 'cd_client' -r "eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJmNjUzNjgwZC05YTIwLTQ0NmEtYTRhMC0xNDg5MGJmZGExYjMtciIsInN1YiI6IjQ2NDQyNjQ3LWU3ZDktNDkxZC1iNzgxLTJhMzEzZDdiYzk1MCIsInNjb3BlIjpbIm9wZW5pZCIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciIsInJvdXRpbmcucm91dGVyX2dyb3Vwcy5yZWFkIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbG91ZF9jb250cm9sbGVyLndyaXRlIiwiZG9wcGxlci5maXJlaG9zZSIsInNjaW0ud3JpdGUiXSwiaWF0IjoxNDY4MTk0MjkxLCJleHAiOjE0NzA3ODYyOTEsImNpZCI6ImNmIiwiY2xpZW50X2lkIjoiY2YiLCJpc3MiOiJodHRwOi8vdWFhLjUyLjUzLjI0Ni4yNS54aXAuaW8vb2F1dGgvdG9rZW4iLCJ6aWQiOiJ1YWEiLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX25hbWUiOiJhZG1pbiIsIm9yaWdpbiI6InVhYSIsInVzZXJfaWQiOiI0NjQ0MjY0Ny1lN2Q5LTQ5MWQtYjc4MS0yYTMxM2Q3YmM5NTAiLCJyZXZfc2lnIjoiNmQ1YzdlMzAiLCJhdWQiOlsiY2YiLCJvcGVuaWQiLCJzY2ltIiwiY2xvdWRfY29udHJvbGxlciIsInVhYSIsInJvdXRpbmcucm91dGVyX2dyb3VwcyIsInBhc3N3b3JkIiwiZG9wcGxlciJdfQ.CEAQz4B1kKJeVIqtCx5K4z5DYAh4jFk_uITnWbaYabjXikcfs5sHYPnBo823fomJHlyVkiyznPFjrugU8ZAMeA1Ju5mvcFMgxYaxQ6C-yXeU1EtCucuyd2VYqRUoROAtmadwJQPPqktWZYSGIxRg1kVeg_w_wYjyLePEcZeoO2w"
./cf target -o pcfdev-org -s pcfdev-space
./cf push -f manifest.yml
